# -*- coding: utf-8 -*-
"""Demo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tY27jzknKj_OHP0nFlqCEr_Yv6cezL3P

This Is My First Demo
"""

print('Hello World')

pwd

cd/content/gt_db/s01

from PIL import Image

im = Image.open('01.jpg')
display(im)

pip list

import pandas as pd
url ="https://raw.githubusercontent.com/COVID19-Malta/COVID19-Data/master/COVID-19%20Malta%20-%20Aggregate%20Data%20Set.csv"
github_data = pd.read_csv(url)
github_data.head(10)